Feature/tag image action
it-at-m/.github pull request #47
Opened 2024-10-28 12:54 UTC by simonhir

**Description**

Add action for tagging a existing image.

Example run: https://github.com/it-at-m/refarch/actions/runs/11554187044

2024-10-28 13:23 UTC, devtobi requested changes

2024-10-28 13:23 UTC, devtobi commented on .github/actions/action-tag-image/action.yaml
> +  registry-username:
Could we provide the value of `github.actor` as a default here? Or isnt this possible?

2024-10-28 13:23 UTC, devtobi commented on .github/actions/action-tag-image/action.yaml
> +  registry-password:
Could we provide the value of `secrets.GITHUB_TOKEN` as a default here?

2024-10-28 13:23 UTC, devtobi commented on .github/actions/action-tag-image/action.yaml
> +    required: true
Could we provide "latest" as a default value here?

2024-10-28 13:23 UTC, devtobi commented on .github/actions/action-tag-image/action.yaml
> +  steps:
I think for consistency it would be good to add the repository checkout here as well. See the other custom actions for reference. But I don't know if it is best practice.

2024-10-28 13:23 UTC, devtobi commented on workflow-templates/tag-image.yaml
Wouldn't it be better to add another layer of abstraction by providing a reusable workflow with a `workflow_call` trigger and then simplify the actual workflow template even more by just triggering the reusable workflow? See the other workflows for reference.

2024-10-28 13:41 UTC, hupling commented on .github/actions/action-tag-image/action.yaml
> +        docker push ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}:${{ inputs.new-tag }}
this looks very complicatet. first you need to pull, then tag, then push.

with skopeo you can do everything in one line https://github.com/containers/skopeo . it is available on the github runner

2024-10-28 13:45 UTC, hupling commented
@it-at-m/sps whtat's your opinion

2024-10-28 14:01 UTC, devtobi commented on .github/actions/action-tag-image/action.yaml
> +        docker push ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}:${{ inputs.new-tag }}
Actually I think skopeo is not the right solution here, as it still requires using a custom container image and script. If skopea is available as ready-to-use action then we could think about it. On the other hand I really like the plain use of docker commands because it makes it really understandable about what is going on.

2024-10-28 14:22 UTC, hupling commented on .github/actions/action-tag-image/action.yaml
> +        docker push ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}:${{ inputs.new-tag }}
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#tools

I don't know what you mean Skopeo 1.13.3 and Docker Client 26.1.3 is installed on the runner. in the script there is nothing about install docker.

2024-10-28 14:36 UTC, simonhir commented on .github/actions/action-tag-image/action.yaml
> +  steps:
The checkout isn't required for this action as it doesn't work with any content of the repository

2024-10-28 14:38 UTC, simonhir commented on workflow-templates/tag-image.yaml
Nearly every call from the templates is direct to the actions.
Also i see no real advantage in that, when correctly versioning this repository, while introducing additional complexity.

2024-10-28 14:48 UTC, simonhir commented on .github/actions/action-tag-image/action.yaml
> +        docker push ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}:${{ inputs.new-tag }}
Nice suggestion didn't know that.
I implemented that for the refarch repository for testing: https://github.com/it-at-m/refarch/pull/236

2024-10-28 15:25 UTC, devtobi commented on .github/actions/action-tag-image/action.yaml
> +        docker push ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}:${{ inputs.new-tag }}
Ah sorry. I didn't know skopeo is part of the runner image by default. Thats a nice addition!

2024-10-28 17:34 UTC, hupling commented
Actually I had it here https://github.com/it-at-m/sps-backend/blob/test-neu/.github/workflows/tag-image.yaml

I think if there is a error you need to do a new release. The image is immutable. 
You need to delete the Git Tag, release notes, etc. If you make a rerelease. 

For example there was an error in the gitlab runner 15.5.0. So I needed to install version 15.5.2 with the bugfix. The image 15.5.0 is always immutable

2024-10-29 06:10 UTC, simonhir commented
> The image is immutable.

Actually it was your suggestion to delete broken images?

2024-10-29 10:33 UTC, devtobi commented on .github/actions/action-tag-image/action.yaml
> +  steps:
Ah ok that makes sense. :) Thanks for clarifying.

2024-10-30 13:51 UTC, ejcsid commented
> The image is immutable

That's true. But the image tag isn't. I think it's ok to just re-tag "latest" (or any other tag) to another image if necessary. But: I'm not sure if we should provide it within the templates. It may be misunderstanding. May be better to document how re-tag could be done?

2025-01-24 08:30 UTC, hupling commented
ich hätte den jetzt geclosed. weil wir ja jetzt mit npm und maven immer eine Version Release und nicht nach Umgebung taggen. Daher finde ich ein Image umtaggen unötig

@ejcsid letztendlich deine Entscheidung, ob wir den Mergen oder Closen.

2025-01-24 08:52 UTC, simonhir commented
Can be closed from my side i just will leave it as custom action for the refarch repo 👍

2025-01-24 08:57 UTC, closed without merging

2025-02-13 09:30 UTC, hupling commented
@ejcsid vielleicht brauchen wir das doch noch für Auto-Rollouts in Deployments