85 unify naming of actions templates etc
it-at-m/.github pull request #88
Opened 2024-12-19 13:33 UTC by hupling

**Description**

refractore templates

**Reference**

Issues #85

2024-12-19 13:34 UTC, hupling commented
@ejcsid  please review

2025-01-08 10:12 UTC, ejcsid requested changes
@hupling names of Actions and Workflows should be readable and not seperated with `-`. names of Jobs and Variables as well the filenames should be separated with `-`, Please check again for all files, I think this was a misunderstanding.

2025-01-08 10:29 UTC, hupling commented on .github/actions/action-build-image/action.yml
> +name: action-build-image
```suggestion
name: "Build Docker Image"
```

2025-01-08 10:30 UTC, hupling commented on .github/actions/action-maven-build/action.yml
> +name: action-maven-build
```suggestion
name: Compliance check and build test
```

2025-01-08 10:31 UTC, hupling commented on .github/actions/action-npm-build/action.yml
> +name: "action-npm-build"
```suggestion
name: Compliance check and build test
```

2025-01-14 10:40 UTC, hupling commented
@ejcsid please review

2025-01-14 12:34 UTC, hupling commented on workflow-templates/maven-node-build.properties.json
>    "name": "Maven-Node-Build",
```suggestion
  "name": "maven-node-build",
```

2025-01-14 12:35 UTC, ejcsid approved these changes

2025-01-14 12:36 UTC, merged